
spring:
  application:
    name: payment-service

  datasource:
    url: jdbc:postgresql://payment_db:5432/payment_db
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

server:
  port: 8086
payment:
  vnPay:
    url: 'https://sandbox.vnpayment.vn/paymentv2/vpcpay.html'
    tmnCode: '58X4B4HP'
    secretKey: 'VRLDWNVWDNPCOEPBZUTWSEDQAGXJCNGZ'
    returnUrl: 'http://payment-service:8086/api/payment/vn-pay-callback'
    version: 2.1.0
    command: pay
    orderType: other
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 5
logging:
  level:
    com.uet.longhoanglekim.paymentservice.*: debug